#!/usr/bin/env node
// check-basemap.mjs — every tile host in the generated basemap style must be in
// the source registry.
//
// WHY THIS EXISTS (R1 in docs/SOURCE_COVERAGE_REVIEW.md). `web/public/basemap/
// style.json` is GENERATED by scripts/sync-data.mjs and was committed with the
// LandsD and Esri tile URLs HARDCODED in that generator. The consequence was
// quiet and one-directional: the five registry entries that describe the map's
// actual basemap (`landsd_basemap_tiles`, `landsd_label_tiles`,
// `landsd_imagery_tiles`, `esri_world_imagery`, `carto_dark_style`) read as
// "referenced by nothing", and if LandsD moved a path then NOTHING in the repo
// needed editing to notice — `validate_config.py` walks sources.json, not this
// generated file, so it would have stayed green while the map went blank.
//
// That is the same shape as Pitfall 27's dead CSS selector: a reference that
// looks live and matches nothing. sync-data.mjs now derives the templates from
// sources.json and throws when an entry is missing, so the generator side is
// fixed; this check is the OTHER direction — it reads the artefact that actually
// ships and proves its hosts are registry hosts, so a future edit to the
// generator cannot reintroduce a hardcoded URL without failing the build.
//
// It also asserts the tile-order contract, because getting it backwards produces
// a plausible map in the WRONG PLACE rather than an error: LandsD is {z}/{x}/{y},
// Esri is {z}/{y}/{x}.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, "..");
const root = join(web, "..");

const registry = JSON.parse(readFileSync(join(root, "sources.json"), "utf8"));
const registryHosts = new Set(
  (registry.sources ?? [])
    .map((s) => {
      try {
        return new URL(String(s.url)).host;
      } catch {
        return null;
      }
    })
    .filter(Boolean),
);

const style = JSON.parse(readFileSync(join(web, "public", "basemap", "style.json"), "utf8"));

const failures = [];
const rows = [];

/** The Worker proxy wraps a tile URL in `?url=<encoded>`. Unwrap it so the check
 *  reads the REAL upstream host — checking only the Worker host would pass for
 *  every tile ever routed through it, including a hardcoded one. */
function upstreamOf(tileUrl) {
  const m = /[?&]url=([^&]+)/.exec(tileUrl);
  if (!m) return tileUrl;
  try {
    return decodeURIComponent(m[1]);
  } catch {
    return tileUrl;
  }
}

for (const [id, src] of Object.entries(style.sources ?? {})) {
  for (const raw of src.tiles ?? []) {
    const upstream = upstreamOf(raw);
    let host;
    try {
      host = new URL(upstream.replace(/\{[a-z]\}/g, "0")).host;
    } catch {
      failures.push(`${id}: unparseable tile URL ${upstream}`);
      continue;
    }
    const inRegistry = registryHosts.has(host);
    if (!inRegistry) failures.push(`${id}: host ${host} is NOT in sources.json`);
    rows.push(`${id} → ${host}${inRegistry ? "" : "  ✗"}`);
  }
}

// Order contract. These are facts about the providers, not derivable from a URL,
// and the wrong order silently relocates the map.
const ORDER = {
  "landsd-topo": "{z}/{x}/{y}",
  "landsd-label-tc": "{z}/{x}/{y}",
  "landsd-imagery": "{z}/{x}/{y}",
  "esri-imagery": "{z}/{y}/{x}",
};
for (const [id, want] of Object.entries(ORDER)) {
  const src = style.sources?.[id];
  if (!src) {
    failures.push(`${id}: missing from the basemap style`);
    continue;
  }
  const tpl = upstreamOf(src.tiles[0] ?? "");
  // Compare the TOKEN SEQUENCE, not the URL's tail: LandsD templates end
  // `{z}/{x}/{y}.png`, so a suffix test fails on a perfectly correct template
  // (it did, on the first run of this check).
  const tokens = (tpl.match(/\{[a-z]\}/g) ?? []).join("/");
  if (tokens !== want) failures.push(`${id}: tile order should be "${want}", got "${tokens || "none"}"`);
}

// The two mandatory basemap layers must exist and be raster sources: an empty
// `sources` block would make every check above vacuously pass.
if (!style.sources?.["landsd-topo"]) failures.push("no landsd-topo source — the Hong Kong basemap is missing");
if (style.version !== 8) failures.push(`style version is ${style.version}, expected 8`);

if (failures.length) {
  console.error("basemap style FAILED:");
  for (const f of failures) console.error("  ✗ " + f);
  process.exit(1);
}
console.log(`basemap OK: ${rows.length} tile sources, every host in sources.json (${registryHosts.size} registry hosts)`);
for (const r of rows) console.log("  · " + r);
