#!/usr/bin/env python3
"""build_lcsd.py - LCSD leisure facilities from CSDI into one compact GeoJSON pair.

WHY THIS EXISTS: the 康文署 layer (Phase 1a of the roadmap, 2026-10-06). The
venue feeds (venues.xml / venue.json / smartplay) carry NO coordinates - measured:
`<latitude />` and `<longitude />` are empty tags, and ALS geocoding a place name
is unreliable (3/21 wrong in a live test). The CSDI LCSD datasets are the OFFICIAL
geometry, which is both more accurate and better provenance than a top-1 geocode.

WHY NINE DATASETS AND NOT THIRTEEN. Nine of the thirteen registered LCSD sources
are CSDI spatial services with names + addresses. The other four (venues.xml,
venue_master, court_booking, smartplay) are value feeds without coordinates; they
stay data, they do not become map dots.

FIELDS FOLLOW THE POPUP CONTRACT in overlays.ts: `Name` is the bold title,
`Foo_tc`/`Foo_en` pairs render as labelled rows in the active language. A field
with no value is dropped, so the popup never shows an empty row.

RUNS ON THE PC, NOT THE WORKER: CSDI sends no CORS header on these services, and
a one-off reference dataset has no business costing a request per page load.

Usage:  python build_lcsd.py            # write ../data/lcsd_facilities.geojson (+ areas)
        python build_lcsd.py --check     # verify the committed files match upstream count
"""
import json, os, sys, urllib.parse, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(HERE, "..", "data")
OUT = os.path.join(OUTDIR, "lcsd_facilities.geojson")       # points -> the layer
OUT2 = os.path.join(OUTDIR, "lcsd_facility_areas.geojson")  # polygons -> future layer
BASE = "https://portal.csdi.gov.hk/server/rest/services/common"

# kind -> (CSDI service id, layer, tc, en)
SOURCES = {
    "sports":    ("lcsd_rcd_1629267205215_31341", 0, "體育館", "Sports Centres"),
    "tennis":    ("lcsd_rcd_1629267205215_84141", 0, "網球場", "Tennis Courts"),
    "badminton": ("lcsd_rcd_1629267205214_38344", 0, "羽毛球場", "Badminton Courts"),
    "basketball": ("lcsd_rcd_1629267205215_38105", 0, "籃球場", "Basketball Courts"),
    "library":   ("lcsd_rcd_1629267205214_44807", 0, "圖書館", "Libraries"),
    "museum":    ("lcsd_rcd_1629267205214_78787", 0, "博物館", "Museums"),
    "park":      ("lcsd_rcd_1629267205215_19292", 0, "公園", "Parks"),
    "camp":      ("lcsd_rcd_1629267205214_83172", 0, "渡假營", "Holiday Camps"),
    "bbq":       ("lcsd_rcd_1634540957025_61259", 0, "燒烤場", "BBQ Sites"),
}


def fetch(svc_id, layer):
    url = (f"{BASE}/{svc_id}/FeatureServer/{layer}/query?"
           + urllib.parse.urlencode({"where": "1=1", "outFields": "*",
                                     "returnGeometry": "true", "f": "geojson",
                                     "outSR": "4326"}))
    req = urllib.request.Request(url, headers={"User-Agent": "HKCityMonitor/1.0"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.loads(r.read().decode("utf-8"))


def props(kind, tc, en, a: dict) -> dict:
    """The popup contract: Name (bold), then _tc/_en pairs. Empty values dropped."""
    p = {}
    name_tc, name_en = str(a.get("NameTC") or "").strip(), str(a.get("NameEN") or "").strip()
    p["Name"] = name_tc or name_en or (tc + "（未命名）")
    if name_tc: p["Name_tc"] = name_tc
    if name_en: p["Name_en"] = name_en
    p["Type_tc"], p["Type_en"] = tc, en
    d_tc, d_en = str(a.get("DistrictTC") or "").strip(), str(a.get("DistrictEN") or "").strip()
    if d_tc: p["District_tc"] = d_tc
    if d_en: p["District_en"] = d_en
    ad_tc, ad_en = str(a.get("AddressTC") or "").strip(), str(a.get("AddressEN") or "").strip()
    if ad_tc: p["Address_tc"] = ad_tc
    if ad_en: p["Address_en"] = ad_en
    return p


def build():
    feats, per = [], {}
    for kind, (svc, layer, tc, en) in SOURCES.items():
        gj = fetch(svc, layer)
        n = 0
        for f in gj.get("features", []):
            if not f.get("geometry"):
                continue
            feats.append({"type": "Feature", "geometry": f["geometry"],
                          "properties": props(kind, tc, en, f.get("properties") or {})})
            n += 1
        per[kind] = n
    return {"type": "FeatureCollection",
            "_comment": ("LCSD leisure facilities from CSDI (official HK government open data). "
                         "Generated by scripts/build_lcsd.py - do not hand-edit. "
                         "k = sports | tennis | badminton | basketball | library | museum | park | camp | bbq"),
            "features": feats}, per


def main():
    doc, per = build()
    if "--check" in sys.argv:
        for path in (OUT, OUT2):
            if not os.path.exists(path):
                print("MISSING", path); return 1
        return 0
    areas = [f for f in doc["features"] if f["geometry"]["type"] in ("Polygon", "MultiPolygon")]
    pins = [f for f in doc["features"] if f["geometry"]["type"] in ("Point", "MultiPoint")]
    assert len(areas) + len(pins) == len(doc["features"]), "a feature is neither an area nor a pin"
    for path, feats in ((OUT, pins), (OUT2, areas)):
        sub = {"type": "FeatureCollection", "_comment": doc["_comment"], "features": feats}
        b = json.dumps(sub, ensure_ascii=False, separators=(",", ":"))
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(b)
        named = sum(1 for f in feats if f["properties"].get("Name"))
        print(f"wrote {os.path.basename(path):28} {len(b.encode('utf-8')):>9,} bytes  {len(feats):>4} features  named {named}/{len(feats)}")
        assert named == len(feats), "a feature lost its name - the popup would be blank"
    for k, n in per.items():
        print(f"  {k:12} {n} fetched upstream")
    return 0


if __name__ == "__main__":
    sys.exit(main())
