#!/usr/bin/env python3
"""build_facilities.py - Hong Kong key facilities into one compact GeoJSON.

WHY THIS EXISTS: the freight and airport modes had no facility geometry at all, so the
panels talked about container terminals and approach areas while the map showed only
camera dots. Source is CSDI (official), which the project already depends on.

WHY ONLY THREE DATASETS. Probed every candidate on CSDI (catalog.db, 1144 rows). Five
were spatial and reachable. Public Piers (531) and Coordinates of ferry piers (74)
carry exactly one attribute each - STRUCTURE_ = "HP077", STOP_ID = "101101" - with no
name, no operator, no type. 605 anonymous dots is visual noise, not information, so they
are deliberately NOT shipped. Measured counts, 2026-09-27:
  Public Cargo Working Areas  mardep_rcd_1638859086572_29125  polygon  120
  HKIA Approach Restricted    mardep_rcd_1730966846483_6820   polygon    8
  Oil Storage Installations   bd_rcd_1630980890272_70649      point     23
  = 151 features, every one of them carrying a name or a rule the popup can state.

WHY `Vacant` IS DROPPED. The cargo-area service also returns a live berth vacancy flag
(Vacant: Y/N, 120 berths). It is real and it is useful - but this file is static. A live
flag baked into a committed snapshot is a stale number presented as current, which is the
one thing this project must not do. The berths ship as durable infrastructure; live
vacancy needs a collector with a cadence and a timestamp, and belongs in its own layer.

RUNS ON THE PC, NOT THE WORKER. CSDI sends no CORS header on these services, and a
one-off reference dataset has no business costing a request per page load.

Usage:  python build_facilities.py            # write ../data/facilities.geojson
        python build_facilities.py --check     # verify the committed file matches
"""
import json, os, re, sys, urllib.parse, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(HERE, "..", "data")
OUT = os.path.join(OUTDIR, "facility_areas.geojson")
OUT2 = os.path.join(OUTDIR, "facility_pins.geojson")
BASE = "https://portal.csdi.gov.hk/server/rest/services/common"

# kind -> (service id, layer, geom, how to build the popup fields)
SOURCES = {
    "cargo_area": ("mardep_rcd_1638859086572_29125", 0, "polygon",
                   lambda a: {"Name": str(a.get("berth_id", "?")),
                              "Type_tc": "公眾貨物裝卸區", "Type_en": "Public Cargo Working Area"}),
    "approach":   ("mardep_rcd_1730966846483_6820", 0, "polygon",
                   lambda a: {"Name": str(a.get("OBJNAM", "Airport Approach Restricted Area")),
                              "Restriction": str(a.get("INFORM", ""))[:200]}),
    "oil":        ("bd_rcd_1630980890272_70649", 0, "point",
                   lambda a: {"Name_tc": str(a.get("DATASET_TC") or ""),
                              "Name_en": str(a.get("DATASET_EN") or ""),
                              "Address_tc": str(a.get("ADDRESS_TC") or ""),
                              "Address_en": str(a.get("ADDRESS_EN") or "")}),
}


# THE PROPERTY KEYS ARE THE POPUP CONTRACT, not free choices. overlays.ts attributeHtml reads
# the bold title out of a field literally named `Name`, renders every other field as a labelled
# row, and understands the CSDI `Foo_tc` / `Foo_en` triple. Short keys (k/n/x) render as
# "未命名" plus raw unlabelled keys - exactly the unreadable popup that path was written to avoid.
# So: cargo berths and approach areas take the publisher's own identifier or name verbatim under
# `Name` (a berth code is not a proper noun to translate), and oil installations carry both
# languages because the publisher ships both.

def fetch(svc_id, layer):
    url = (f"{BASE}/{svc_id}/FeatureServer/{layer}/query?"
           + urllib.parse.urlencode({"where": "1=1", "outFields": "*",
                                     "returnGeometry": "true", "f": "geojson",
                                     "outSR": "4326"}))
    req = urllib.request.Request(url, headers={"User-Agent": "HKCityMonitor/1.0"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.loads(r.read().decode("utf-8"))


def build():
    feats, per = [], {}
    for kind, (svc, layer, geom, mk) in SOURCES.items():
        gj = fetch(svc, layer)
        for f in gj.get("features", []):
            if not f.get("geometry"):
                continue
            attrs = mk(f.get("properties") or {})
            feats.append({"type": "Feature", "geometry": f["geometry"],
                          "properties": {kk: vv for kk, vv in attrs.items() if vv}})
        per[kind] = len(gj.get("features", []))
    return {"type": "FeatureCollection",
            "_comment": ("Hong Kong key facilities from CSDI (official HK government open data). "
                         "Generated by scripts/build_facilities.py - do not hand-edit. "
                         "k = cargo_area | approach | oil. Berth vacancy is NOT included: see that script."),
            "features": feats}, per


def main():
    doc, per = build()
    body = json.dumps(doc, ensure_ascii=False, separators=(",", ":"))
    if "--check" in sys.argv:
        for path in (OUT, OUT2):
            if not os.path.exists(path):
                print("MISSING", path); return 1
        return 0
    # TWO FILES, because a layer's `geom` picks ONE renderer: a polygon layer draws
    # vl-{id}-fill/-line/-label and a point layer goes through the generic cluster path.
    # Mixing them in one file means one of the two definitely does not draw.
    areas = [f for f in doc["features"] if f["geometry"]["type"] in ("Polygon", "MultiPolygon")]
    pins = [f for f in doc["features"] if f["geometry"]["type"] in ("Point", "MultiPoint")]
    assert len(areas) + len(pins) == len(doc["features"]), "a feature is neither an area nor a pin"
    for path, feats in ((OUT, areas), (OUT2, pins)):
        sub = {"type": "FeatureCollection", "_comment": doc["_comment"], "features": feats}
        b = json.dumps(sub, ensure_ascii=False, separators=(",", ":"))
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(b)
        named = sum(1 for f in feats if f["properties"].get("Name") or f["properties"].get("Name_tc"))
        print(f"wrote {os.path.basename(path):26} {len(b.encode('utf-8')):>9,} bytes  {len(feats):>3} features  named {named}/{len(feats)}")
        assert named == len(feats), "a feature lost its name - the popup would be blank"
    for k, n in per.items():
        print(f"  {k:12} {n} fetched upstream")
    return 0


if __name__ == "__main__":
    sys.exit(main())
