#!/usr/bin/env python3
"""build_carpark_info.py — slim TD's car park basic info into what the app reads.

WHY THIS EXISTS (MEASURED 2026-09-27). The front end fetched
resource.data.one.gov.hk/td/carpark/basic_info_all.json on EVERY cold load: 554,726 bytes,
the single largest item on the critical path and 30% of the whole first paint. Measured with
`npm run measure:boot`.

`parseCarpark` reads THREE fields out of those 554 records — park_id, name_tc, name_en. The
rest of the payload is name_sc / displayAddress_* / district_* / latitude / longitude /
contactNo / opening_status / height / remark_* / website_* / carpark_photo, and the two
heaviest are `remark_*` at 52% of the content (mostly the empty string "高度限制: \\n") and the
duplicated simplified-Chinese copies at 21%.

So this writes the merge key and the two names, compact, and nothing else. 554,726 bytes ->
~36,000. The full upstream file is still ONE curl away and is not being censored; it is being
declined at the point where a browser was downloading it for three fields.

WHY IT IS COMMITTED RATHER THAN CRONNED. The registry says cadence "irregular" — these are car
park NAMES and coordinates, not a feed. TD changes them when a car park opens, closes or is
renamed. A committed file that a human refreshes is the honest shape; a cron would spend a
request a day to discover nothing changed.

WHAT IT REFUSES TO DO. It exits non-zero rather than writing a file whose record count differs
from upstream, or that has a record with no park_id, or that drops a name both languages were
missing. A silently shrunken file means car parks quietly vanish from the panel, and the panel
would look fine — it would just show fewer rows. `--check` re-fetches and compares against the
committed file without writing anything, which is the form to run in CI or by hand.

    python3 scripts/build_carpark_info.py           # fetch, slim, write data/carpark_info.json
    python3 scripts/build_carpark_info.py --check   # fetch and compare; write nothing
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

UPSTREAM = "https://resource.data.one.gov.hk/td/carpark/basic_info_all.json"
OUT = Path(__file__).resolve().parent.parent / "data" / "carpark_info.json"

# The three fields parseCarpark actually reads. Adding one here is the whole change needed to
# ship it — but check the parser first, or you are adding bytes for nothing.
KEEP = ("park_id", "name_tc", "name_en")


def fetch() -> dict:
    req = urllib.request.Request(UPSTREAM, headers={"User-Agent": "hk-city-monitor/0.2"})
    with urllib.request.urlopen(req, timeout=45) as r:
        # The upstream serves a UTF-8 BOM. json.loads rejects it; utf-8-sig does not. This cost a
        # confusing "Unexpected UTF-8 BOM" on first contact.
        return json.loads(r.read().decode("utf-8-sig"))


def slim(payload: dict) -> list[dict]:
    parks = payload.get("car_park")
    if not isinstance(parks, list) or not parks:
        raise SystemExit(f"upstream carried no car_park list (got {type(parks).__name__})")

    out: list[dict] = []
    missing_id = 0
    missing_names = 0
    for p in parks:
        pid = (p.get("park_id") or "").strip()
        if not pid:
            missing_id += 1
            continue
        rec = {"park_id": pid}
        for k in ("name_tc", "name_en"):
            v = (p.get(k) or "").strip()
            if v:
                rec[k] = v
        if "name_tc" not in rec and "name_en" not in rec:
            # parseCarpark skips these anyway, so shipping them would be bytes the app never
            # reads. Counted, not silently dropped.
            missing_names += 1
            continue
        out.append(rec)

    # Refuse to write anything surprising. A shrunken file is invisible in the UI: the panel
    # renders fewer rows and looks entirely healthy.
    if missing_id:
        raise SystemExit(f"REFUSING: {missing_id} upstream record(s) had no park_id")
    if missing_names:
        raise SystemExit(f"REFUSING: {missing_names} record(s) had neither name_tc nor name_en")
    if len(out) < len(parks) * 0.95:
        raise SystemExit(f"REFUSING: {len(out)} kept of {len(parks)} upstream — a >5% drop is a schema change, not a refresh")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="compare against the committed file; write nothing")
    args = ap.parse_args()

    parks = slim(fetch())
    body = {"_comment": (
        "GENERATED by scripts/build_carpark_info.py from TD's basic_info_all.json — do not hand-edit. "
        "Slimmed to the three fields parseCarpark reads (park_id / name_tc / name_en): the upstream file "
        "is 554KB and 52% of its content is empty height-limit remarks, which a browser was downloading "
        "on every cold load. Re-run the script to refresh; --check verifies without writing."
    ), "car_park": parks}
    text = json.dumps(body, ensure_ascii=False, separators=(",", ":")) + "\n"

    if args.check:
        if not OUT.exists():
            print(f"MISSING: {OUT} — run without --check to generate it")
            return 1
        have = json.loads(OUT.read_text(encoding="utf-8"))
        hb = {p["park_id"]: p for p in have["car_park"]}
        nb = {p["park_id"]: p for p in parks}
        gone = sorted(set(hb) - set(nb))
        added = sorted(set(nb) - set(hb))
        changed = [k for k in set(hb) & set(nb) if hb[k] != nb[k]]
        print(f"committed {len(hb)}  upstream {len(nb)}  gone {len(gone)}  new {len(added)}  renamed {len(changed)}")
        for k in gone[:10]:
            print(f"  GONE  {k}  {hb[k].get('name_tc', '')}")
        for k in changed[:10]:
            print(f"  RENAMED  {k}  {hb[k].get('name_tc', '')} -> {nb[k].get('name_tc', '')}")
        return 0 if not (gone or changed) else 1

    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(OUT.parent.parent)}  {len(parks)} parks  {len(text)} chars ")
    print(f"  on disk: {OUT.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
