#!/usr/bin/env python3
"""HK City Monitor — Worker target-host whitelist builder.

The Cloudflare Worker (worker/) is a CORS proxy for the sources.json entries
whose "fetch" is "proxy". SECURITY.md §4 requires it to refuse any URL whose
host is not in the registry — an open proxy gets used as a free relay, which
is worse than the CORS problem it solves. The whitelist is therefore DERIVED
from sources.json, never hand-maintained: run this after editing sources.json.

The whitelist is host-level (the scheme+host of every "url" and every
"candidates" entry), because that is the granularity SECURITY.md specifies.
It intentionally includes browser-mode hosts too: the LandsD tile hosts are
browser-mode (ACAO=*) yet COST.md routes their tiles through the Worker for
edge caching, so they must pass the same check.

Run:  python3 build_worker_whitelist.py           # writes worker/src/whitelist.generated.js
      python3 build_worker_whitelist.py --check   # self-check, no writes
"""
import json
import os
import sys
from urllib.parse import urlparse

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCES = os.path.join(ROOT, "sources.json")
OUT = os.path.join(ROOT, "worker", "src", "whitelist.generated.js")

HEADER = (
    "// GENERATED by scripts/build_worker_whitelist.py from sources.json — do not edit.\n"
    "// Regenerate: py -3 scripts/build_worker_whitelist.py   (repo root)\n"
)


def collect_hosts():
    with open(SOURCES, encoding="utf-8") as f:
        registry = json.load(f)["sources"]
    hosts = set()
    for entry in registry:
        urls = [entry.get("url")] + list(entry.get("candidates") or [])
        for u in urls:
            if not u:
                continue
            host = urlparse(u).netloc
            if host:
                hosts.add(host.lower())
    return sorted(hosts)


def render(hosts):
    lines = [HEADER, "export default [\n"]
    lines += [f'  "{h}",\n' for h in hosts]
    lines.append("]\n")
    return "".join(lines)


def self_check(hosts):
    # These three are load-bearing: immd_cp_queue is the Run 1 acceptance source,
    # the LandsD hosts carry the basemap tiles and the 3D tilesets.
    for required in ("secure1.info.gov.hk", "mapapi.geodata.gov.hk", "data.map.gov.hk"):
        assert required in hosts, f"required host missing from whitelist: {required}"
    assert len(hosts) >= 60, f"host count suspiciously low: {len(hosts)}"
    assert all(" " not in h and "/" not in h for h in hosts), "malformed host"
    assert len(hosts) == len(set(hosts)), "duplicate hosts"
    print(f"self-check OK ({len(hosts)} hosts)")


def main():
    check_only = "--check" in sys.argv
    hosts = collect_hosts()
    self_check(hosts)
    if check_only:
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(hosts))
    print(f"{os.path.relpath(OUT, ROOT)}: {len(hosts)} hosts, {os.path.getsize(OUT)} bytes")


if __name__ == "__main__":
    main()
