#!/usr/bin/env python3
"""Generate ATTRIBUTION.md from sources.json.

Why generated: the attribution duty is a FACT about each source, and sources.json
is where a source is declared. A hand-kept attribution list drifts the moment a
source is added — and the HKSAR open-data terms require the attribution, so a
drift is a licence breach, not a cosmetic problem.

The 10 sources with no `license` are listed separately and marked as unverified.
scripts/apply_licenses.py leaves them blank on purpose ("a wrong licence is worse
than none"); this file must show that gap rather than hide it behind a heading.

Run:  python scripts/build_attribution.py
"""
from __future__ import annotations

import io
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "sources.json"
OUT = ROOT / "ATTRIBUTION.md"


def main() -> int:
    data = json.loads(io.open(SRC, encoding="utf-8").read())
    sources = data["sources"] if isinstance(data, dict) else data

    by_licence: dict[str, list[dict]] = defaultdict(list)
    unverified: list[dict] = []
    for s in sources:
        lic = s.get("license")
        if lic:
            by_licence[lic].append(s)
        else:
            unverified.append(s)

    total = len(sources)
    lines: list[str] = []
    w = lines.append

    w("# Attribution")
    w("")
    w("All data displayed by this project belongs to its publisher and is used under the terms listed")
    w("below. **Open data published by HKSAR Government departments requires attribution**, so this")
    w("file is a licence requirement, not a courtesy.")
    w("")
    w("> Generated by `scripts/build_attribution.py` from `sources.json` — **do not edit by hand**.")
    w("> Adding a source requires only re-running the script, so this document and the code cannot")
    w("> disagree.")
    w("")
    w("## Summary")
    w("")
    w(f"- Total sources: **{total}**")
    w(f"- Licence confirmed: **{total - len(unverified)}**")
    w(f"- Unverified (intentionally blank): **{len(unverified)}**")
    w("")
    w("## Licence register")
    w("")
    for lic in sorted(by_licence, key=lambda k: (-len(by_licence[k]), k)):
        w(f"### {lic}")
        w("")
        w(f"{len(by_licence[lic])} source(s).")
        w("")
        w("| Source | Name | URL |")
        w("|---|---|---|")
        for s in sorted(by_licence[lic], key=lambda x: x["id"]):
            name = (s.get("name_en") or s.get("name") or "").replace("|", "/")
            url = s.get("url") or ""
            url_cell = f"[link]({url})" if url.startswith("http") else (url or "—")
            w(f"| `{s['id']}` | {name} | {url_cell} |")
        w("")

    w("## Unverified licences")
    w("")
    w("`scripts/apply_licenses.py` leaves these blank deliberately — **a wrong licence is worse than")
    w("none**. Verify each publisher's own terms before use.")
    w("")
    w("| Source | Publisher / host | Name |")
    w("|---|---|---|")
    from urllib.parse import urlparse

    for s in sorted(unverified, key=lambda x: x["id"]):
        host = urlparse(s.get("url") or "").hostname or "(no URL)"
        name = (s.get("name_en") or s.get("name") or "").replace("|", "/")
        w(f"| `{s['id']}` | {host} | {name} |")
    w("")
    w("## Basemaps and place names")
    w("")
    w("- Basemap and place-name labels: **map data from the Lands Department** (LandsD)")
    w("- Aerial imagery and 3D digital maps: Lands Department")
    w("- Alternative basemaps: © OpenStreetMap contributors (ODbL), © CARTO")
    w("")
    w("## This project")
    w("")
    w("- Source code: **AGPL-3.0-only**, see `LICENSE`")
    w("- Architecture inspired by [World Monitor](https://github.com/koala73/worldmonitor)")
    w("  (AGPL-3.0, by Elie Habib). This is an independent project, not an official World Monitor")
    w("  product.")
    w("- **No affiliation** with the Government of the Hong Kong Special Administrative Region,")
    w("  including its 「AI城市大腦」 programme.")
    w("")

    text = "\n".join(lines)
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s: %d bytes, %d licences, %d unverified" % (OUT.name, len(text.encode("utf-8")), len(by_licence), len(unverified)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
