#!/usr/bin/env python3
"""build_aqhi.py - AQHI monitoring station positions from CSDI.

WHY THIS EXISTS: the AQHI value feeds carry station NAMES with no coordinates
(measured: past_24_pollutant.js has StationID + names only), and ALS geocoding
of place names is unreliable (3/21 wrong in a live test, 2026-10-06). CSDI's
"Air Quality Monitoring Network of Hong Kong" is the OFFICIAL station geometry,
which is both accurate and proper provenance.

WHY NO LIVE VALUES HERE. AQHI changes hourly and this file is a static
reference. The live values come from the aqhi_city_dashboard adapter, which
merges this file by station name at refresh time - so the numbers on the map
are as fresh as the API, never a baked snapshot.

RUNS ON THE PC, NOT THE WORKER: CSDI sends no CORS header on these services,
and a one-off reference dataset has no business costing a request per page load.

Usage:  python build_aqhi.py            # write ../data/aqhi_stations.geojson
        python build_aqhi.py --check     # verify the committed file exists
"""
import json, os, sys, urllib.parse, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(HERE, "..", "data")
OUT = os.path.join(OUTDIR, "aqhi_stations.geojson")
SVC = "epd_rcd_1629267205214_40635"
BASE = "https://portal.csdi.gov.hk/server/rest/services/common"


def fetch():
    url = (f"{BASE}/{SVC}/FeatureServer/0/query?"
           + urllib.parse.urlencode({"where": "1=1", "outFields": "*",
                                     "returnGeometry": "true", "f": "geojson",
                                     "outSR": "4326"}))
    req = urllib.request.Request(url, headers={"User-Agent": "HKCityMonitor/1.0"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.loads(r.read().decode("utf-8"))


def props(a: dict) -> dict:
    p = {}
    name_tc, name_en = str(a.get("NAME_TC") or "").strip(), str(a.get("NAME_EN") or "").strip()
    p["Name"] = name_tc or name_en or "監測站（未命名）"
    if name_tc: p["Name_tc"] = name_tc
    if name_en: p["Name_en"] = name_en
    # The publisher's own station class, verbatim (general vs roadside).
    st_tc, st_en = str(a.get("SEARCH01_TC") or "").strip(), str(a.get("SEARCH01_EN") or "").strip()
    if st_tc: p["Type_tc"] = st_tc
    if st_en: p["Type_en"] = st_en
    ad_tc, ad_en = str(a.get("ADDRESS_TC") or "").strip(), str(a.get("ADDRESS_EN") or "").strip()
    if ad_tc: p["Address_tc"] = ad_tc
    if ad_en: p["Address_en"] = ad_en
    return p


def main():
    gj = fetch()
    feats = []
    for f in gj.get("features", []):
        if not f.get("geometry"):
            continue
        feats.append({"type": "Feature", "geometry": f["geometry"],
                      "properties": props(f.get("properties") or {})})
    doc = {"type": "FeatureCollection",
           "_comment": ("AQHI monitoring stations from CSDI (official HK government open data). "
                        "Generated by scripts/build_aqhi.py - do not hand-edit. Live AQHI values "
                        "are merged by the aqhi_city_dashboard adapter, never baked here."),
           "features": feats}
    if "--check" in sys.argv:
        return 0 if os.path.exists(OUT) else (print("MISSING", OUT), 1)[1]
    body = json.dumps(doc, ensure_ascii=False, separators=(",", ":"))
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(body)
    named = sum(1 for f in feats if f["properties"].get("Name"))
    print(f"wrote {os.path.basename(OUT):28} {len(body.encode('utf-8')):>8,} bytes  {len(feats):>3} stations  named {named}/{len(feats)}")
    assert named == len(feats), "a station lost its name - the popup would be blank"
    return 0


if __name__ == "__main__":
    sys.exit(main())
